<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/03_Slicing_Indexing_1D_2D.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
<

# 03 — Slicing e Indexación (1D y 2D)

- Indexación básica y booleana
- Slicing por rangos y saltos
- `None` para agregar ejes: `n x 1` vs `n x None`
- Diferencias entre 1D y 2D



In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
idx = arr[[0,2,4]]
mask = arr % 2 == 1
(arr[1:], arr[::2], idx, arr[mask])


NameError: name 'array' is not defined

In [5]:
# None agrega un eje nuevo
v = np.arange(5)
col = v[:, None]   # n x 1
row = v[None, :]   # 1 x n
(v.shape, col.shape, row.shape)


((5,), (5, 1), (1, 5))

In [6]:
# 2D slicing
M = np.arange(1, 13).reshape(3,4)
(
    M,
    M[0, :],      # primera fila
    M[:, 0],      # primera columna
    M[1:, 1:3],   # submatriz
)


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 2, 3, 4]),
 array([1, 5, 9]),
 array([[ 6,  7],
        [10, 11]]))