<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/03_Slicing_Indexing_1D_2D.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
<

# 03 — Slicing e Indexación (1D y 2D)

- Indexación básica y booleana
- Slicing por rangos y saltos
- `None` para agregar ejes: `n x 1` vs `n x None`
- Diferencias entre 1D y 2D



In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
idx = arr[[0,2,4]]
mask = (arr % 3 == 1) | (arr % 3 == 2)
(arr[1:], arr[::2], idx, arr[mask])
mask # muestra aquellos valores que cumplen con el criterio del mask


array([ True,  True, False,  True,  True])

In [31]:
# None agrega un eje nuevo
v = np.arange(5)
v = v.reshape(5,1)
col = v[:, None]   # n x 1
row = v[None, :]   # 1 x n
(v, v.shape, col.shape, row.shape, row, col)



(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1),
 (5, 1, 1),
 (1, 5, 1),
 array([[[0],
         [1],
         [2],
         [3],
         [4]]]),
 array([[[0]],
 
        [[1]],
 
        [[2]],
 
        [[3]],
 
        [[4]]]))

In [49]:
# 2D slicing
M = np.arange(1, 101).reshape(10,10)
(
    M,
    M[0, :],      # primera fila
    M[:, 0],      # primera columna
    M[1:2, 1:2],   # submatriz  excluye 1 e incluye 2
)


(array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]),
 array([[12]]))

In [34]:
t = np.ones(5)
t

array([1., 1., 1., 1., 1.])