<a target="_blank" href="https://colab.research.google.com/github/sonder-art/fdd_p25/blob/main/professor/numpy/notebooks/04_Operaciones_Basicas_y_Broadcasting.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


# 04 — Operaciones básicas y Broadcasting

- Aritmética elemento a elemento
- Comparaciones
- Producto matricial `@`
- Broadcasting en operaciones



In [2]:
import numpy as np

x = np.array([-1,0,1,2])
(x*2, x**2, x+2, -x)


(array([-2,  0,  2,  4]),
 array([1, 0, 1, 4]),
 array([1, 2, 3, 4]),
 array([ 1,  0, -1, -2]))

In [8]:
# Comparaciones y where
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
np.where(a == b)
(a[a==b], a==b)


(array([1, 4, 5]), array([ True, False, False,  True,  True]))

In [14]:
# Producto matricial
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[2,0,0],[0,2,0],[0,0,2]])
(A, A @ B)


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [19]:
# Broadcasting
v = np.arange(4)
M = np.ones((3,4))
(v, M, M + v)


(array([0, 1, 2, 3]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]]))